version: 0.0
os: linux
files:
  - source: /nginx.conf
    destination: /home/ec2-user/node-website
  - source: /package.json
    destination: /home/ec2-user/node-website
  - source: /dist/
    destination: /home/ec2-user/node-website/dist
  - source: /ssl/
    destination: /home/ec2-user/node-website/ssl
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
