version: 0.2

phases:
  install:
    commands:
      - npm install
      - pip install --upgrade awscli
  pre_build:
    commands:
      #- npm test
  post_build:
    commands:
      - npm run build:ssr
artifacts:
  type: zip
  files:
    - package.json
    - nginx.conf
    - appspec.yml
    - scripts/*
    - dist/**/*
    